name: CI
on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

permissions:
  issues: write
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3
        with:
          name: action.yml
          path: action.yml

  test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    needs: [build]
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
        with:
          name: action.yml
          path: .

      - name: Create issue content
        env:
          OS: ${{ matrix.os }}
        run: echo "#[CI] test $OS" > issue.md

      - name: Test create issue from file
        id: ciff
        uses: peter-evans/create-issue-from-file@433e51abf769039ee20ba1293a088ca19d573b7f # v4
        with:
          title: '[CI] test ${{ matrix.os }}'
          content-filepath: ./issue.md

      - name: Close Issue
        uses: ./
        with:
          issue-number: ${{ steps.ciff.outputs.issue-number }}
          comment: |
            [CI]
            test ${{ matrix.os }}
          labels: |
            wontfix
            ci-test
